"""Print the Ignition addresses of every populated SunSpec point, for building tags by hand.

    python -m sim.register_map              # plain text
    python -m sim.register_map --markdown   # the table used in docs/points/site1-register-map.md

Addresses assume Ignition's default one-based addressing: the wire address plus one (Phase 1 finding 13). The unit ID is
the number in front of the dot, so `[Inv1]1.HR40085` is unit 1 on the device named Inv1.
"""
import argparse
import random
import sys
from datetime import datetime, timezone

from sim import sunspec
from sim.model import PlantModel, SiteConfig
from sim.sunspec_layouts import LAYOUTS

# Ignition's Modbus data-type designators. HR, HRUS, and HRUI have been exercised against the simulator; HRI has not.
HEADER = """# Site 1 register map (Phase 1)

Generated by `python -m sim.register_map --markdown`; do not edit by hand. These are the points the simulator serves
(ADR 0006 and 0009). Every other point in each SunSpec model is served as "not implemented".

- **Addresses are Ignition's.** They assume Ignition's default one-based addressing, which is the wire address plus one
  (Phase 1 finding 13). A tag path looks like `[Inv1]1.HR40085`: the device name in brackets, the unit ID before the dot.
- **Register types.** `HR` is a signed 16-bit register, `HRUS` an unsigned 16-bit one, and `HRUI` an unsigned 32-bit one.
  All three were read correctly in Ignition on 2026-10-03; in particular a SunSpec 32-bit value (the `WH` energy counter)
  came through with the high word first, which is Ignition's default. `HRI` (signed 32-bit) has not been tested; no
  populated point uses it.
- **Designer's data type names** differ from the JSON ones: Short is Int2, Integer is Int4, Long is Int8, Double is Float8.
  Use Integer for 16-bit registers and Long for 32-bit ones.
- **Scale factors.** Real value = register x 10^SF. The scale factor is the point named in the last column, or a fixed
  number where the model fixes it.
- **Units 2 to 4** are identical to unit 1 apart from the unit ID in front of the dot.

"""
DESIGNATOR = {
    "int16": "HR", "sunssf": "HR", "uint16": "HRUS", "enum16": "HRUS", "bitfield16": "HRUS", "acc16": "HRUS",
    "int32": "HRI", "acc32": "HRUI", "uint32": "HRUI", "enum32": "HRUI", "bitfield32": "HRUI",
}
CONFIG = SiteConfig()  # this document is for Site 1; other plants have other unit IDs (ADR 0014 decision 9)
INVERTER_UNITS, WEATHER_UNIT, METER_UNIT = sunspec.unit_ids(CONFIG)
DEVICES = (
    ("Inverter (units %d to %d; unit 1 shown)" % (INVERTER_UNITS[0], INVERTER_UNITS[-1]), 1),
    ("Weather station (unit %d)" % WEATHER_UNIT, WEATHER_UNIT),
    ("POI meter (unit %d)" % METER_UNIT, METER_UNIT),
)


def point_rows(unit, models):
    """(model, point, Ignition address, register type, units, scale factor) for each populated point."""
    registers = sunspec.device_registers(models)
    for model_id, values in models:
        if model_id == 1:
            continue  # the common block is identification only
        start = sunspec.find_model(registers, model_id)
        offset = 2
        for name, kind, size, sf, units in LAYOUTS[model_id]:
            if name in values and kind != "string":
                address = sunspec.BASE_ADDRESS + start + offset + 1  # one-based for Ignition
                if sf is None:
                    sf_text = "-"
                elif isinstance(sf, int):
                    sf_text = "fixed %d" % sf
                else:
                    sf_text = sf
                yield model_id, name, "%d.%s%d" % (unit, DESIGNATOR[kind], address), kind, units or "", sf_text
            offset += size


def snapshot_models():
    state = PlantModel(SiteConfig(clouds_enabled=False)).step(datetime(2026, 6, 21, 18, 50, tzinfo=timezone.utc), 1.0)
    return sunspec.all_device_models(state, CONFIG, random.Random(0), noise=False)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--markdown", action="store_true")
    args = parser.parse_args(argv)
    devices = snapshot_models()
    if args.markdown:
        sys.stdout.reconfigure(newline="\n")  # the repo keeps every file LF, also on Windows
        print(HEADER, end="")
    for title, unit in DEVICES:
        rows = list(point_rows(unit, devices[unit]))
        if args.markdown:
            print("## %s\n" % title)
            print("| Model | Point | Ignition address | Register type | Units | Scale factor |")
            print("|---|---|---|---|---|---|")
            for model_id, name, address, kind, units, sf in rows:
                print("| %d | `%s` | `%s` | %s | %s | %s |" % (model_id, name, address, kind, units or "", sf))
            print()
        else:
            print("\n%s" % title)
            for model_id, name, address, kind, units, sf in rows:
                print("  %3d  %-12s %-14s %-10s %-6s %s" % (model_id, name, address, kind, units, sf))


if __name__ == "__main__":
    main()
