"""Generate sim/sunspec_layouts.py from the public SunSpec model definitions (needs the network).

    python sim/tools/gen_sunspec_layouts.py

Source: https://github.com/sunspec/models (json/model_<id>.json). For models with a repeating group (302 and 303) one
repetition is written, which is one sensor. Each entry is (point name, type, size in registers, scale factor, units); the
scale factor is the name of the point that holds it, a fixed number, or None. The model's ID and length registers are not
listed because the register map writes them itself.
"""
import json
import pathlib
import urllib.request

MODELS = (1, 103, 123, 203, 302, 303, 307)
TYPE_SIZE = {"uint16": 1, "int16": 1, "sunssf": 1, "enum16": 1, "bitfield16": 1, "pad": 1, "acc16": 1,
             "uint32": 2, "int32": 2, "acc32": 2, "enum32": 2, "bitfield32": 2, "float32": 2}
URL = "https://raw.githubusercontent.com/sunspec/models/master/json/model_%d.json"
OUT = pathlib.Path(__file__).resolve().parents[1] / "sunspec_layouts.py"


def fetch_layouts():
    layouts = {}
    for model_id in MODELS:
        group = json.load(urllib.request.urlopen(URL % model_id, timeout=30))["group"]
        points = list(group["points"])
        for sub in group.get("groups", []):
            points += sub["points"]  # one repetition of the repeating group
        body = []
        for point in points:
            if point["name"] in ("ID", "L"):
                continue
            size = point.get("size") or TYPE_SIZE[point["type"]]
            body.append((point["name"], point["type"], size, point.get("sf"), point.get("units")))
        layouts[model_id] = body
    return layouts


def render(layouts):
    lines = [
        '"""SunSpec model layouts used by the simulator. GENERATED by sim/tools/gen_sunspec_layouts.py; do not edit.',
        "",
        "Source: https://github.com/sunspec/models (json/model_<id>.json). Each entry is (point name, type, size in",
        "registers, scale factor, units), in register order, without the model's ID and length registers. The scale",
        "factor is the name of the point that holds it, a fixed number, or None.",
        '"""',
        "",
        "LAYOUTS = {",
    ]
    for model_id, body in layouts.items():
        lines.append("    %d: [" % model_id)
        for name, kind, size, sf, units in body:
            lines.append("        (%r, %r, %d, %r, %r)," % (name, kind, size, sf, units))
        lines.append("    ],")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    text = render(fetch_layouts())
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote %s (%d lines)" % (OUT, text.count("\n")))
